version: '3.3'
services:
  ecommerce-database:
    # platform: linux/x86_64
    image: mysql:latest
    restart: always
    environment:
      MYSQL_DATABASE: 'ecommerce-database'
      MYSQL_ROOT_PASSWORD: 'ecommerce'
    ports:
      - '3306:3306'
    volumes:
      - ecommerce-database-volume:/var/lib/mysql
volumes:
 ecommerce-database-volume: