package app 

var schema = `
CREATE TABLE IF NOT EXISTS Users (
  id INT NOT NULL AUTO_INCREMENT,
  username VARCHAR(500) NOT NULL,
  email VARCHAR(500) NOT NULL,
  password VARCHAR(500) NOT NULL,
  resetToken VARCHAR(500) NOT NULL,
  confirmToken VARCHAR(500) NOT NULL,
  confirmed TINYINT NOT NULL DEFAULT 0,
  blocked TINYINT NOT NULL DEFAULT 0,
  cellPhone VARCHAR(500) NOT NULL,
  firstName VARCHAR(500) NOT NULL,
  lastName VARCHAR(500) NOT NULL,
  stripeAccountId VARCHAR(500) NOT NULL,
  createdAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP(),
  updatedAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP(),
  PRIMARY KEY (id),
  UNIQUE INDEX id_UNIQUE (id ASC) VISIBLE,
  UNIQUE INDEX username_UNIQUE (username ASC) VISIBLE,
  UNIQUE INDEX email_UNIQUE (email ASC) VISIBLE,
  UNIQUE INDEX resetToken_UNIQUE (resetToken ASC) VISIBLE,
  UNIQUE INDEX confirmToken_UNIQUE (confirmToken ASC) VISIBLE
);

`